version: '3.8'

services:
  app:
    build:
      context: .
    container_name: my-app-container
    ports:
      - "8080:8080"  # Thay đổi theo yêu cầu của ứng dụng

    command: [ "npx", "playwright", "test"]
