version: '3'
services:
  test_ui:
    build:
      context: .
    image: my-app-image:latest
    container_name: my-app-container
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./playwright-report:/app/playwright-report  # Chia sẻ thư mục báo cáo
    command: [ "npx", "playwright", "test"]
