version: '3'
services:
  playwright:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: [ "npx", "playwright", "test", "--ui", "--ui-host=0.0.0.0", "--ui-port=8080" ]
