version: '3'
services:
  playwright:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./playwright-report:/app/playwright-report  # Chia sẻ thư mục báo cáo
    command: [ "npx", "playwright", "test"]
