name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2' 
      - name: Set up
        run: docker-compose build test_ui
      - name: Run Test
        run: docker-compose up test_ui
      - name: Down Docker Compose
        run: docker-compose down
      - uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
