name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Docker Compose
        run: |
          apt-get update
          apt-get install -y docker-compose 
      - name: Set up
        run: docker-compose build test_ui
      - name: Kiểm tra nội dung thư mục /app
        run: docker-compose run test_ui ls /app
      - name: Run Test
        run: docker-compose up test_ui
      - name: Down Docker Compose
        run: docker-compose down
      - uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
